# POST https://hajame-bloglogger.herokuapp.com/api/blogs
 POST http://localhost:3001/api/blogs
content-type: application/json

{
  "title": "Animated line drawings with OpenCV",
  "author": "Oona Räisänen",
  "url": "https://www.windytan.com/2017/12/animated-line-drawings-with-opencv.html",
  "likes": 99
}